### ISSUE TITLE
setTransitionName not working within RecyclerView

### ISSUE THREAD

**Issue by percula** [andkulikov/Transitions-Everywhere#62]
First off, thank you for this amazing library. It is simple and beautiful!

Now onto the issue: I added setTransitionName() to my RecyclerVIew and it helped, but it didn't catch all the views. My ViewHolder consists of the parent item View, an ImageView, and a TextView. I used setTransitionName() on all three, making sure each name is unique:
```
holder.mNameView.setText(name);
TransitionManager.setTransitionName(holder.mView, name);
TransitionManager.setTransitionName(holder.mIconView, name + "icon");
TransitionManager.setTransitionName(holder.mNameView, name + "name");
```

I have [uploaded a short video](https://youtu.be/mWn6F8YB13U) to demonstrate the issue. 
Also, the three files I use TransitionsEverywhere in my project are [here](https://github.com/percula/Planter/blob/master/GardenPlanner/app/src/main/java/com/perculacreative/peter/gardenplanner/ui/CalendarFragment.java), [here](https://github.com/percula/Planter/blob/master/GardenPlanner/app/src/main/java/com/perculacreative/peter/gardenplanner/recyclerview/PlantCategoryRecyclerAdapter.java), and [here](https://github.com/percula/Planter/blob/master/GardenPlanner/app/src/main/java/com/perculacreative/peter/gardenplanner/utility/Utility.java), just search for "TransitionManager".

Perhaps I am doing something wrong or it's a bug.

**Comment by andkulikov** [comment]
Hi, 
Its hard to use transitions for recycler view because recycler view has some complex asynchronous layout logics.
So, why don't you just use build-in animation from recyclerview? I mean in your case you could
1) call appropriate notifyInserted, notifyChanged methods from the adapter
2) do the same things in a more clever way with [DiffUtils](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html)
3) apply [stable ids](https://www.reddit.com/r/androiddev/comments/2lr8bf/what_does_recyclerview_sethasstableids_do_and_why/) for adapter.

**Comment by percula** [comment]
Thanks @andkulikov, great suggestions and I'll give one of those options a shot. Probably DiffUtils, seems easiest to implement in my app.
