### ISSUE TITLE
Crash on Recycler view expand animation

### ISSUE THREAD

**Issue by Sottti** [andkulikov/Transitions-Everywhere#74]
Apparently, this is common to both libraries.

https://issuetracker.google.com/issues/37129527

**Comment by andkulikov** [comment]
@Sottti Hey. Are you sure its still crashing with the latest Transitions-Everywhere? I fixed a similar issue in version 1.7.3. its related to any visibility transition like Fade. 
Also I am trying to reproduce it, but in my local build Plaid always stuck on the progress bar instead of comments like its unable to load them

**Comment by andkulikov** [comment]
the fix is https://github.com/andkulikov/Transitions-Everywhere/commit/0d977dd7dddee12bdb02f78b1d4c10d649190b26

**Comment by andkulikov** [comment]
Ok, I managed to make Plaid works. And I see that its crashing on com.andkulikov:transitionseverywhere:1.7.2
but not on the latest
com.andkulikov:transitionseverywhere:1.7.6
So please check next time before creating a bug is it really reproducible.
I will also add a comment into the google issue, to help to fix it support library as well
