### ISSUE TITLE
Crash on Samsung Galaxy tablet, Android 9.0 

### ISSUE THREAD

**Issue by vadimkorovinsky** [andkulikov/Transitions-Everywhere#98]
Reproduced only on Samsung Galaxy tablet S5e 10.5 SM-T725 with Android 9.0 
We use 1.8.0 library version

After call TransitionManager.endTransitions() we have exception:

file: Transition.java, 
method: void forceToEnd(@Nullable ViewGroup sceneRoot) {
line: AnimationInfo info = runningAnimators.valueAt(i);
exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=19

**Comment by andkulikov** [comment]
Hi!
The current version of Transitions-Everywhere is based on androidx.transition library and this bug was fixed there as part of the version 1.1.0-rc02 here: https://android.googlesource.com/platform/frameworks/support/+/8b1665dd70b2c3bda327d44d8228b60f0dd3c399
Unfortunately I am not going to maintain 1.8.0 version of Transitions-Everywhere so I would suggest you to migrate to the newest version (please note that it could mean you need to migrate from support libraries to AndroidX if you didn't already)
